// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kujjqfvicrazqitxkdwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ampxZnZpY3JhenFpdHhrZHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDUwNjUsImV4cCI6MjA2MTUyMTA2NX0.p1rMYOU6rp6im1PaJyeQydxldKeQ4WXbOinDtsDUxl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);